const knex = require('knex');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const db = knex({
  client: 'mysql2',
  connection: {
    host: process.env.DB_HOST,
    port: Number(process.env.DB_PORT) || 3306,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    ssl: { rejectUnauthorized: false }
  }
});

async function run() {
  try {
    console.log('Connecting to DB...');
    
    // Find expenses that look like they were auto-generated by the staff payment feature
    const expenses = await db('expenses')
      .where('description', 'like', 'Staff Salary:%')
      .orWhere('bill_number', 'like', 'STAFF-%');
      
    console.log(`Found ${expenses.length} auto-generated staff expenses in the expenses table.`);
    
    if (expenses.length > 0) {
      const ids = expenses.map(e => e.expense_id);
      console.log('Deleting expense IDs:', ids);
      await db('expenses').whereIn('expense_id', ids).del();
      console.log('Successfully deleted duplicates from expenses table!');
    } else {
      console.log('No duplicates found based on description/bill_number.');
      
      // Look for categories that might be "Staff Salary" or "Salary"
      const cats = await db('expense_categories').where('category_name', 'like', '%salar%').orWhere('category_name', 'like', '%staff%');
      if (cats.length > 0) {
        const catIds = cats.map(c => c.category_id);
        const manualExpenses = await db('expenses').whereIn('category_id', catIds);
        console.log(`Found ${manualExpenses.length} manual expenses under Salary categories:`, manualExpenses);
        
        if (manualExpenses.length > 0) {
          const ids = manualExpenses.map(e => e.expense_id);
          console.log('Deleting manual expense IDs:', ids);
          await db('expenses').whereIn('expense_id', ids).del();
          console.log('Successfully deleted manual salary expenses!');
        }
      }
    }
  } catch (err) {
    console.error('Error:', err);
  } finally {
    await db.destroy();
  }
}

run();
